### ISSUE TITLE
No names - 

### ISSUE THREAD

**Issue by cenkdominic** [seboettg/citeproc-php#38]
There are certain citeable things that have no names attached to them - articles from The Economist for example - so they have no first and last name. 
Right now if I try to convert them using citeproc-php I get this fatal error: 

`Uncaught Seboettg\CiteProc\Exception\CiteProcException: Illegal argument. Name has no family name. in /vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/Util/NameHelper.php:114`

Commenting out the lines in NameHelper.php removes the error, but the resulting citation looks weird. 

Optimally what should happen is that the characters in and after the name should simply not appear. So `,. [article name]` etc. just becomes `[article name]`. 

I will attempt to find a workaround, I just thought I’d bring it to your attention.

**Comment by seboettg** [comment]
Hi Cenk!
I'm happy to apply your suggestion, but before I do, I want to reproduce the problem in order to exclude that the reason for your issue are erroneous input data.
> There are certain citeable things that have no names attached to them - articles from The Economist for example - so they have no first and last name.

As described on [csl schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json#L77), a CSL name variable (e.g. author) usually has the properties family name and given name. That's the reason of the thrown exception. Is there no author the author property of your CSL data should be empty or should not exist.

It would be a great help if you could post some sample CSL input data and the stylesheet which causing the error.

**Comment by cenkdominic** [comment]
Whoops! Seems this was a misunderstanding on my part. Thanks for the thoughtful response, and sorry for being an idiot.

**Comment by seboettg** [comment]
No problem. Feel free to ask if you have any questions or running in trouble!
