### ISSUE TITLE
bibtex encoding error

### ISSUE THREAD

**Issue by annakuglerin** [seboettg/citeproc-php#65]
German umlaute are not encoded, e.g. ‘ä’ should be encoded as ‘{"a}’.
Thus, during import e.g. into endnote it generates errors.

see: https://github.com/pkp/pkp-lib/issues/4853

**Comment by seboettg** [comment]
Thank you for that issue. 
I'm sorry, but I guess this is not an issue of citeproc-php, since CSL does not intent to convert the input data into another input format. If I remember correctly, there are no rules, neither in CSL in generally nor in the BibTeX stylesheet in particular, to convert umlauts. Thus, citeproc-php is not able to convert it.
@annakuglerin possibly there are other ways to find a solution. Please explain the specific issue in more detail.

**Comment by seboettg** [comment]
@annakuglerin Did you find a solution for your issue? Can I close this ticket?

**Comment by seboettg** [comment]
@annakuglerin I'm going to close this ticket now. If you have further question, feel free to reopen this ticket or create a new one.
