### ISSUE TITLE
... is reduced to . in citations

### ISSUE THREAD

**Issue by RazielleS** [seboettg/citeproc-php#90]
I have set up an example for you here: https://github.com/RazielleS/citeproc-bug-demo

On the first entry in the demo.csl, there is a title with `...` inside.
This library converts this to only a single dot, which is not intended.
I have tried with a demo on https://editor.citationstyles.org/searchByName/. There it does not cut out the dots.

**Comment by seboettg** [comment]
Hi @RazielleS!
There is an UTF-8 character for "three dots" (HTML entity &hellip;) Simply replace '...' (three characters) by '…' (one character) and it will work as expected.

**Comment by RazielleS** [comment]
Hi @seboettg 
Thank you, I have changed it accordingly. This seems to work fine for now.
Would be glad if this gets changed eventually though, so we can remove the replacement workaround in our codebase again.

**Comment by seboettg** [comment]
Hi @RazielleS,
Shit in - shit out. To be honest, I don't see citeproc-php as having the responsibility to clean up bad input data. This is a bottomless pit. Especially since, depending on the application scenario, very different needs would arise. The scope of these requirements might justify a separate application.
